name: bare-datascience
channels:
  - conda-forge
  - defaults
dependencies:
    - python=3.9
    - pip>=19.0
    - jupyter
    - numpy
    - scikit-learn
    - scipy
    - pandas
    - pandas-datareader
    - matplotlib
    - seaborn
    - opencv
    - selenium
        